/* SPDX-License-Identifier: GPL-2.0-only
 *
 * Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
 */

#ifndef _QAIC_MHI_BACKPORT_FLAGS_H_
#define _QAIC_MHI_BACKPORT_FLAGS_H_

#include <linux/version.h>
#include <generated/utsrelease.h>

/*
 * Parse UTS_UBUNTU_RELEASE_ABI
 */
#ifdef UTS_UBUNTU_RELEASE_ABI
#ifndef UBUNTU_ABI
#define CONCAT_HLP(x, y) x##y
#define HEXIFY(z) CONCAT_HLP(0x, z)
#define UBUNTU_ABI HEXIFY(UTS_UBUNTU_RELEASE_ABI)
#endif //UBUNTU_ABI defined
#define SYSFS_ABI_CHECK HEXIFY(139)
#endif //UTS_UBUNTU_RELEASE_ABI defined

#if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 9, 0) && \
		!(defined(RHEL_MAJOR) && (RHEL_MAJOR == 7) && (RHEL_MINOR >= 9)))
#define _QBP_NEED_BIT_FIELD_PREPGET
#endif

#if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 19, 0))
#define _QBP_REDEF_IDA_FREE
#endif

#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 7, 0) && \
		!(defined(RHEL_MAJOR) && \
			RHEL_MAJOR == 8 && RHEL_MINOR >= 5))
#define _QBP_NEED_MHI_MODALIAS_DEV_ID
#endif

#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 8, 0)) && \
	!(defined(CONFIG_SUSE_VERSION) && \
		CONFIG_SUSE_VERSION == 15 && CONFIG_SUSE_PATCHLEVEL >= 3) && \
	!(defined(RHEL_MAJOR) && (RHEL_MAJOR == 8) && (RHEL_MINOR >= 4))
#define _QBP_NEED_FSLEEP
#endif /* LINUX_VERSION_CODE < 5.8.0 && SUSE_VERSION<15.3 && RHEL_VERSION < 8.4 */

#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 10, 0)  && \
	(LINUX_VERSION_CODE < KERNEL_VERSION(4, 9, 260) || \
		LINUX_VERSION_CODE >= KERNEL_VERSION(4, 10, 0)) && \
	(LINUX_VERSION_CODE < KERNEL_VERSION(4, 14, 224) || \
		LINUX_VERSION_CODE >= KERNEL_VERSION(4, 15, 0)) && \
	(LINUX_VERSION_CODE < KERNEL_VERSION(4, 19, 179) || \
		LINUX_VERSION_CODE >= KERNEL_VERSION(4, 20, 0)) && \
	(LINUX_VERSION_CODE < KERNEL_VERSION(5, 4, 103) || \
		LINUX_VERSION_CODE >= KERNEL_VERSION(5, 5, 0)) && \
	!(defined(CONFIG_SUSE_VERSION) && \
		CONFIG_SUSE_VERSION == 15 && CONFIG_SUSE_PATCHLEVEL >= 3) && \
	!(defined(RHEL_MAJOR) && (RHEL_MAJOR == 8 && (RHEL_MINOR >= 5))) &&  \
	!(defined(UBUNTU_ABI) && UBUNTU_ABI >= SYSFS_ABI_CHECK && \
		LINUX_VERSION_CODE <= KERNEL_VERSION(4, 15, 18) && \
		LINUX_VERSION_CODE >= KERNEL_VERSION(4, 15, 0))
#define _QBP_NEED_SYSFS_EMIT
#endif

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 4))
#define _QBP_HAS_PRANDOM_U32
#endif

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(6, 3, 0))
#define _QBP_HAS_UEVENT_CONST_DEV
#endif

#endif /* end _QAIC_MHI_BACKPORT_FLAGS_H_ */
